const TEMPLATE_COLLECTION = "templates";
const OBJECT_COLLECTION = "objects";
const USERS_COLLECTION = "users";
const LOGS_COLLECTION = "logs";
const CONFIG_COLLECTION = "config";

const VERSIONS_COLLECTION = "versions";
const GAMES_COLLECTION = "games";
const GAME_PREFIX = "game_";

module.exports = {
	TEMPLATE_COLLECTION,
	OBJECT_COLLECTION,
	USERS_COLLECTION,
	LOGS_COLLECTION,
	CONFIG_COLLECTION,


	VERSIONS_COLLECTION,
	GAMES_COLLECTION
} 

